server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_price
    username: postgres
    password: 12345
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # replace after first run on "none" or "update"
    show-sql: true
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,loggers,logfile
  metrics:
    export:
      prometheus:
        enabled: true