server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: stock-price-loader-service
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

management:
  endpoint:
    logfile:
      enabled: true
      external-file: src/main/resources/logs/logfile.log
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,loggers,logfile
  metrics:
    export:
      prometheus:
        enabled: true

app-config:
  moex:
    stock-price-url: https://iss.moex.com/iss/history/engines/stock/markets/shares
  scheduler:
    stock-price:
      rate: PT5M