version: '3'
services:
  postgres:
    image: library/postgres:13
    container_name: postgres_13
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      monitoring:
        aliases:
          - postgres
    volumes:
# put in explore Win10 \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\
      - ./data:/var/lib/postgresql/data
    expose:
      - 5435
    ports:
      - "5435:5435"
    command:
      -p 5435

  pgadmin:
    container_name: pgadmin4_view_container
    image: dpage/pgadmin4
    restart: on-failure
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      monitoring:
        aliases:
          - pgadmin

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - '9090:9090'
    networks:
      monitoring:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana

networks:
  monitoring:
